# Generated by Django 5.2.7 on 2025-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='page',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='page',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Speech',
        ),
    ]
