# Generated by Django 5.2.7 on 2025-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_sharednote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_tts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='note_tts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
