# Generated by Django 5.2.7 on 2025-10-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='embedded_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
