# Generated by Django 5.2.7 on 2025-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0003_page_embedded_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='page_tts',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='stt_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='stt_summary_tts',
            field=models.URLField(blank=True, null=True),
        ),
    ]
