# Generated by Django 5.2.7 on 2025-11-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0004_doc_page_tts_doc_stt_summary_doc_stt_summary_tts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
    ]
