# Generated by Django 5.2.7 on 2025-11-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0005_remove_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='page_tts',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='page',
            name='embedded_images',
        ),
    ]
