# Generated by Django 5.2.7 on 2025-11-07 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0006_remove_doc_page_tts_remove_doc_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='hidden_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
