# Generated by Django 5.2.7 on 2025-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0007_doc_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='summary_tts',
            field=models.URLField(blank=True, null=True),
        ),
    ]
