# Generated by Django 5.2.7 on 2025-11-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0008_page_summary_page_summary_tts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
