# Generated by Django 5.2.7 on 2025-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0009_alter_board_image_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='end_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
