# Generated by Django 5.2.7 on 2025-11-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0010_doc_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='stt_summary',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='stt_summary_tts',
        ),
        migrations.CreateModel(
            name='SpeechSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.CharField(max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_tts', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speech_summaries', to='lecture_docs.doc')),
            ],
        ),
    ]
