# Generated by Django 5.2.7 on 2025-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0011_remove_doc_stt_summary_remove_doc_stt_summary_tts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_tts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_tts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='summary_tts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speechsummary',
            name='summary_tts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
