# Generated by Django 5.2.7 on 2025-12-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_docs', '0012_alter_board_board_tts_alter_page_page_tts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_tts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
