# Generated by Django 5.2.7 on 2025-10-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('lecture_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='lecture_docs.page'),
        ),
        migrations.AddField(
            model_name='note',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lecture_docs.page'),
        ),
        migrations.AddField(
            model_name='speech',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='lecture_docs.page'),
        ),
    ]
