# Generated by Django 5.2.7 on 2025-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_bookmark_timestamp_sec_bookmark_user_note_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='relative_time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
