# Generated by Django 5.2.7 on 2025-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_bookmark_relative_time_bookmark_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_tts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='stt_tts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
