# Generated by Django 5.2.7 on 2025-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.CharField(choices=[('느림', '느림'), ('보통', '보통'), ('빠름', '빠름')], default='보통', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='voice',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성')], default='여성', max_length=10),
        ),
    ]
