# Generated by Django 5.2.7 on 2025-11-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rate_user_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='font',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='voice',
            field=models.CharField(max_length=10),
        ),
    ]
